git:
  depth: 3
sudo: required
services:
  - docker
env:
  global:
    - DOCKER_REPO=cadasta/zipstream
    - DOCKER_IMG_BRANCH=$DOCKER_REPO:${TRAVIS_BRANCH//\//.}
    - secure: CM/uUNVWMidna83BB+nnfe90h5u8fSxF/rFr+fr6DZK6fjnrq8/N5v6l+VvFGsNlxq66uLB5wYa3u7zQyvMP76YnbqNzZcunGd0q5YAZ/mIQXioqosxtx8tlYGDtr8JLuI2SQR0G/a3XYp9g9fEWABM3qoD3rMY4SiXBK1i4UL+CrxegfiifTSkMybH6paFcrhR4qwe7oJuuRPEdNOVfu77/+HRh8yP/uEpk41vVSNWL25bJsF4T4ej/r4MjhCqkuOsJXFGq0oEjcnPcq9sMruiR1Y9PbmhPJjNY0HyTS6aEBlsb8yRJ+519FkiM+2TPAXDxi62CxojSDjhTzu2EBkwmjuLWaH3LLrUfyVu1V3V41TTlGIYmYeE53pgFkkimRTEhWCtSPrsZbrfiZFs3g+HvS0tH7nyaru6Lx4a1yvsQzC42YqyxvrcNn3J3yhvPCywDv7jdtoVBDy8JoZT5OXSdFGX483LJNigszTJg7xDt0j81QUQS/Tb39agsiY4Aslwnlc7EIa4bgqos1eSfmGQOBX6KyfvGA/pUAJ5FnDeXj/qh/Qr5c5b0knCVhD75MpkWBr2JzPf4e07BQsxb9VQC1gF80EpZRn+db+dn8uKRbrA4VABAVi0olBDqOKaEK9Ect3QuFJiGYziGM+IHD4ZpylD7DxYmkUBSoMcAQhc=
    - secure: PzsPaWJenXFygE4CC7fls5vMzMsqmoxbOjnD99LSy26TAPVaI83dFZ6MQcmUDDhWt3htHxmO+hwpZfiikwwQ5VQLtBhA1BBjQyO8f5YG6UPidT1J3YQaNoLoZLQDWyZUMBBC314RFnw3ITm0pKrRsX2wY8rz0x0Td5ZTSmxy3+bRZkERyslYyL+4kq+qj3wiLMwki8lsdwRDG+/w2Q9OtXNuq7ky3bREWi3t1mix7go2xSRZPYW048yGoIwceTdldEKFuQJ1TXKh+yuzJNEOiY3fB50qOgFrbxkupiIJXCV6sFzxp//lFx/Sb/MzdcJcGqNT2NAniG9WbM/nU+8mV5EY06YjTLdVySZpXLAniLs2KWM/AhJo/p5u7p4/fonVAymQfHfD6fFiUEjzo88lj0uvEF5ZmHGxSzFisTaxqelE0HqgFJjIr9BrvrEbYeDJ07ZZfdLRXd8gH2ntHnZW+k+gY2XCX4J9L8vx5g+yygDf6UjkuNg83VNgKgNFqn+Mb17SnPYsAlcWOidCTOSssPgV+ttwr8n3n4D1+G5oxOqXKxlbG9R3y34LPsERSj3OOaF+IpujRb8lfT0ZnuQyc/wOHiSgm8IdpWE92sgPIgCBRHfTkfBYx8QaR8idBLki+AjD9Dm3LMyDDDjcWxAovWp8/gzCOcA3QXymE7wd7rM=
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
install:
  - docker pull $DOCKER_IMG_BRANCH || docker pull $DOCKER_REPO:master || docker pull $DOCKER_REPO || true
  - docker build --cache-from $DOCKER_IMG_BRANCH -t $DOCKER_IMG_BRANCH .
script:
  - echo "Building $DOCKER_IMG_BRANCH ($TRAVIS_COMMIT)"
  - docker run -t $DOCKER_IMG_BRANCH yarn test:coverage
  - docker run -t $DOCKER_IMG_BRANCH yarn lint
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_IMG_BRANCH;
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker tag $DOCKER_IMG_BRANCH $DOCKER_REPO;
      docker push $DOCKER_REPO;
    fi